import { Product, Collection, Drop } from "./types";

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/#about" },
  { label: "Collection", href: "/collections" },
  { label: "Contact", href: "/contact" },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Jujutsu Kaisen — Gojo Satoru Figure",
    slug: "gojo-satoru-figure",
    price: 89.99,
    comparePrice: 119.99,
    images: ["/products/gojo-figure.jpg"],
    category: "figures",
    tags: ["jjk", "gojo", "figure", "limited"],
    series: "Jujutsu Kaisen",
    inStock: true,
    isFeatured: true,
    badge: "Fan Fave",
    character: "Satoru Gojo",
    description:
      "High-detail 1/8 scale figure of Gojo Satoru in his iconic pose. Hand-painted with premium finish.",
  },
  {
    id: "2",
    name: "One Piece — Luffy Gear 5 Figure",
    slug: "luffy-gear5-figure",
    price: 79.99,
    images: ["/products/luffy-gear5.jpg"],
    category: "figures",
    tags: ["one piece", "luffy", "gear5", "figure"],
    series: "One Piece",
    inStock: true,
    isFeatured: true,
    isDrop: true,
    badge: "New Drop",
    character: "Monkey D. Luffy",
    description:
      "Luffy in his transcendent Gear 5 form. Artfully captures the wild, free energy of the Warrior of Liberation.",
  },
  {
    id: "3",
    name: "Demon Slayer — Tanjiro Haori",
    slug: "tanjiro-haori",
    price: 54.99,
    comparePrice: 69.99,
    images: ["/products/tanjiro-haori.jpg"],
    category: "apparel",
    tags: ["demon slayer", "tanjiro", "haori", "apparel"],
    series: "Demon Slayer",
    inStock: true,
    character: "Tanjiro Kamado",
    description:
      "Premium replica of Tanjiro's iconic checkered haori. Breathable linen-blend fabric.",
  },
  {
    id: "4",
    name: "Attack on Titan — Survey Corps Jacket",
    slug: "survey-corps-jacket",
    price: 74.99,
    images: ["/products/aot-jacket.jpg"],
    category: "apparel",
    tags: ["aot", "survey corps", "jacket", "apparel"],
    series: "Attack on Titan",
    inStock: false,
    badge: "Sold Out",
    character: "Survey Corps",
    description:
      "Official-style Survey Corps embroidered jacket. Available in S–3XL.",
  },
  {
    id: "5",
    name: "Naruto — Akatsuki Ring Set",
    slug: "akatsuki-ring-set",
    price: 34.99,
    images: ["/products/akatsuki-rings.jpg"],
    category: "accessories",
    tags: ["naruto", "akatsuki", "rings", "accessories"],
    series: "Naruto",
    inStock: true,
    character: "Akatsuki",
    description: "Complete set of 10 hand-carved Akatsuki rings. Zinc alloy.",
  },
  {
    id: "6",
    name: "Chainsaw Man — Pochita Plush",
    slug: "pochita-plush",
    price: 24.99,
    images: ["/products/pochita-plush.jpg"],
    category: "collectibles",
    tags: ["chainsaw man", "pochita", "plush"],
    series: "Chainsaw Man",
    inStock: true,
    isFeatured: true,
    badge: "Cozy Pick",
    character: "Pochita",
    description:
      "Extra soft Pochita plush. The perfect cozy companion for your anime shelf.",
  },
  {
    id: "7",
    name: "Naruto — Itachi Uchiha Figure",
    slug: "itachi-uchiha-figure",
    price: 94.99,
    comparePrice: 120.00,
    images: ["/products/itachi-figure.jpg"],
    category: "figures",
    tags: ["naruto", "itachi", "figure", "uchiha"],
    series: "Naruto",
    inStock: true,
    isFeatured: true,
    badge: "Fan Fave",
    character: "Itachi Uchiha",
    description:
      "1/8 scale Itachi Uchiha in Anbu pose. Sharingan eyes rendered in translucent resin.",
  },
  {
    id: "8",
    name: "Naruto — Akatsuki Cloak",
    slug: "akatsuki-cloak",
    price: 89.99,
    comparePrice: 110.00,
    images: ["/products/akatsuki-cloak.jpg"],
    category: "apparel",
    tags: ["naruto", "akatsuki", "cloak", "apparel"],
    series: "Naruto",
    inStock: true,
    character: "Akatsuki",
    description:
      "Full-length Akatsuki cloak with red cloud embroidery. Premium polyester blend. One size fits most.",
  },
  {
    id: "9",
    name: "Naruto — Minato Namikaze Figure",
    slug: "minato-namikaze-figure",
    price: 89.99,
    images: ["/products/minato-figure.jpg"],
    category: "figures",
    tags: ["naruto", "minato", "figure", "4th hokage", "limited"],
    series: "Naruto",
    inStock: true,
    isDrop: true,
    badge: "New Drop",
    character: "Minato Namikaze",
    description:
      "The 4th Hokage immortalised in hand-painted resin. 300 units only. Lightning-speed shipping.",
  },
  {
    id: "10",
    name: "Bleach — Ichigo Bankai Figure",
    slug: "ichigo-bankai-figure",
    price: 99.99,
    images: ["/products/ichigo-figure.jpg"],
    category: "figures",
    tags: ["bleach", "ichigo", "bankai", "figure"],
    series: "Bleach",
    inStock: true,
    isFeatured: true,
    badge: "Fan Fave",
    character: "Ichigo Kurosaki",
    description:
      "Ichigo in Bankai form — Tensa Zangetsu raised, hollow mask half-fractured. 1/8 scale, premium resin.",
  },
  {
    id: "11",
    name: "Bleach — Soul Reaper Shihakushō",
    slug: "soul-reaper-shihakusho",
    price: 64.99,
    images: ["/products/shihakusho.jpg"],
    category: "apparel",
    tags: ["bleach", "soul reaper", "shihakusho", "apparel"],
    series: "Bleach",
    inStock: true,
    character: "Soul Society",
    description:
      "Authentic-weight Shihakushō (Soul Reaper uniform). Satin black cotton. Available in S–3XL.",
  },
  {
    id: "12",
    name: "One Piece — Zoro Three-Sword Set",
    slug: "zoro-three-sword-set",
    price: 49.99,
    images: ["/products/zoro-swords.jpg"],
    category: "accessories",
    tags: ["one piece", "zoro", "swords", "accessories"],
    series: "One Piece",
    inStock: true,
    character: "Roronoa Zoro",
    description:
      "Miniature replica of Zoro's three swords — Wado Ichimonji, Sandai Kitetsu, Shusui. Display stand included.",
  },
  {
    id: "13",
    name: "Chainsaw Man — Denji Nendoroid",
    slug: "denji-nendoroid",
    price: 74.99,
    images: ["/products/denji-nendo.jpg"],
    category: "figures",
    tags: ["chainsaw man", "denji", "nendoroid", "figure"],
    series: "Chainsaw Man",
    inStock: true,
    isFeatured: true,
    character: "Denji",
    description:
      "Chibi-style Denji nendoroid with chainsaws deployed. Includes Pochita companion figure.",
  },
  {
    id: "14",
    name: "Studio Ghibli — Totoro XL Garden Plush",
    slug: "totoro-xl-plush",
    price: 34.99,
    images: ["/products/totoro-plush.jpg"],
    category: "collectibles",
    tags: ["ghibli", "totoro", "plush", "cozy"],
    series: "Studio Ghibli",
    inStock: true,
    badge: "Cozy Pick",
    character: "Totoro",
    description:
      "XL Totoro plush — extra-soft velboa fabric, embroidered details. 45 cm tall. Studio Ghibli licensed.",
  },
  {
    id: "15",
    name: "Studio Ghibli — No-Face Collector Piece",
    slug: "no-face-collector-piece",
    price: 59.99,
    images: ["/products/no-face.jpg"],
    category: "collectibles",
    tags: ["ghibli", "spirited away", "no-face", "collector"],
    series: "Studio Ghibli",
    inStock: true,
    isDrop: true,
    badge: "New Drop",
    character: "No-Face / Kaonashi",
    description:
      "Hand-painted ceramic No-Face figure. Matte black glaze, white mask inlay. 200 units worldwide.",
  },
  {
    id: "16",
    name: "Jujutsu Kaisen — Sukuna Finger Ring Set",
    slug: "sukuna-finger-ring-set",
    price: 39.99,
    images: ["/products/sukuna-rings.jpg"],
    category: "accessories",
    tags: ["jjk", "sukuna", "rings", "accessories"],
    series: "Jujutsu Kaisen",
    inStock: true,
    character: "Ryomen Sukuna",
    description:
      "Set of 3 Sukuna-motif rings — engraved cursed energy sigils. Sterling silver finish.",
  },
];

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: "1",
    name: "Shonen Legends",
    slug: "shonen-legends",
    description: "The icons. The power levels. The vibes.",
    coverImage: "/collections/shonen.jpg",
    productCount: 24,
  },
  {
    id: "2",
    name: "Demon Slayer Universe",
    slug: "demon-slayer",
    description: "Breath styles, haori, and collector gems.",
    coverImage: "/collections/demon-slayer.jpg",
    productCount: 18,
    series: "Demon Slayer",
  },
  {
    id: "3",
    name: "Fandom Streetwear",
    slug: "streetwear",
    description: "Wear your series. Subtle flex, loud love.",
    coverImage: "/collections/streetwear.jpg",
    productCount: 31,
  },
  {
    id: "4",
    name: "Limited Figures",
    slug: "limited-figures",
    description: "Exclusive scale figures. Collector-only drops.",
    coverImage: "/collections/figures.jpg",
    productCount: 12,
  },
];

export const MOCK_DROPS: Drop[] = [
  {
    id: "1",
    name: "Gear 5 Luffy — Limited Run",
    description:
      "The first wave of Gear 5 Luffy 1/8 scale figures. Hand-painted, 300 units only. Register for early access.",
    image: "/drops/gear5-drop.jpg",
    releaseDate: "2025-06-15T18:00:00Z",
    isLive: false,
    requiresRegistration: true,
    registeredCount: 1247,
  },
  {
    id: "2",
    name: "YAA Summer Haori Collection",
    description:
      "Custom haori collab with independent Japanese artists. 8 exclusive designs, strictly limited quantities.",
    image: "/drops/haori-drop.jpg",
    releaseDate: "2025-06-22T12:00:00Z",
    isLive: false,
    requiresRegistration: true,
    registeredCount: 892,
  },
  {
    id: "3",
    name: "Demon Slayer — Nezuko Collector Box",
    description:
      "Premium collector's bundle: Nezuko Kamado hand-painted figure, series art prints, and exclusive stickers. 200 units.",
    image: "/drops/nezuko-box.jpg",
    releaseDate: "2025-07-05T15:00:00Z",
    isLive: false,
    requiresRegistration: true,
    registeredCount: 543,
  },
];

export const ANEMONE_INTRO_MESSAGES = [
  "Nyan~ Welcome to YAA Store! I'm Anemone, your fandom guide 🐱",
  "Looking for something specific? I know every series, every drop.",
  "Ask me about restocks, recs, or just your fave anime 😼",
];
